# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('illustration', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='illustration')),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('town', models.CharField(max_length=255)),
                ('productName', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=10)),
                ('discount', models.CharField(max_length=255)),
                ('logo', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='logo')),
                ('illustration', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='illustration')),
                ('illustration2', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True)),
                ('illustration3', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True)),
                ('illustration4', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True)),
                ('team', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True)),
                ('mainLink', models.URLField()),
                ('website', models.URLField()),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('instagram', models.URLField()),
                ('category', models.ManyToManyField(to='MAIN.Category')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': 'PRODUIT',
            },
            bases=('pages.page', models.Model),
        ),
    ]
