# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='content',
            new_name='presentation_product',
        ),
        migrations.AddField(
            model_name='product',
            name='baseline',
            field=models.CharField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='baseline_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='presentation_product_en',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='product',
            name='presentation_sup',
            field=mezzanine.core.fields.RichTextField(default=False, verbose_name='Presentation Start-up'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='presentation_sup_en',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Presentation Start-up'),
        ),
        migrations.AddField(
            model_name='product',
            name='productName_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
