# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0004_auto_20161107_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='team',
            new_name='team_pic',
        ),
    ]
