# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0005_auto_20161107_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mainLink',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
